### ISSUE TITLE
Add a "good first issue" label

### ISSUE THREAD

**Issue by marziply** [rwf2/Rocket#2278]
**Suggested Changes**

Having a "good first issue" label would help those that would like a good place to start here. It's a pretty common label to have in large projects like this.

**Comment by Guileas** [comment]
I agree with you @marziply it could be a good starting point. 
I personnaly would like to help on the project as I'm using it often for my personal projects but don't know where to start

**Comment by clintonruairi** [comment]
@marziply I agree with you, I'm looking to start contributing but unsure where best to start.

**Comment by Irene-123** [comment]
Can I help in adding a `good first issue` tag?
