### ISSUE TITLE
[Feature Request] Allow route decorator to define a custom HTTP method.

### ISSUE THREAD

**Issue by mehcode** [rwf2/Rocket#232]
Allow the generic `route` decorator to accept _any_ method. I'd be okay with requiring quotes for non-standard methods.

```rust
#[route(FOO, path = "...")]
```

Or

```rust
#[route("FOO", path = "...")]
```

---

Key motivation for this is I have a colleague who uses https://tools.ietf.org/html/draft-snell-link-method-12 in his API definitions. 

There are also a dozen more defined methods that aren't "standard HTTP". It's not reasonable for rocket to have first-class support for any method. I think this is a good middle ground.

**Comment by bytebuddha** [comment]
Hello everybody, has anyone given more though to this? I need this feature, my use case is trying to create a webdav server in my app that can share my application contacts with phones/computers. WebDav makes use of a few custom methods like 'PROPFIND' & 'MKCOL' that i would need to be able to use. 

I have found #619 but after reading the comments left by @SergioBenitez I'm not sure how to move forward with this. I agree that putting a String in Method is not the best idea, but i don't see a way to possibly use a &'static str there. 

My idea is to create a feature gate  (maybe named webdav_methods) that when enabled would add the webdav related http methods to the Methods enum. I don't know much about the internals of the route macros (route, get, post, etc.) but i don't think it would make much sense to provide a macro for these methods if they could be created with just the `#[route(MKCOL, ...)]` macro.

Here is a list of all the Extension Methods would be necessary for this feature

- COPY
- LOCK
- MKCOL
- MOVE
- PROPFIND
- PROPPATCH
- UNLOCK

**Comment by alexandrebouthinon** [comment]
Hello, any updates on this? I am very interested in supporting additional HTTP methods (if you don't want to support defining them via a string). My use case is to be able to declare routes supporting LOCK and UNLOCK methods

**Comment by nanobot248** [comment]
any plans on this? would PRs be appreciated?
basically, i'm not so much interested in custom methods, but including the standard methods (although not the HTTP 1.1 standard) added by other RFCs like webdav - like those listed here: https://webconcepts.info/concepts/http-method/

**Comment by Clivern** [comment]
Me too. I need LOCK and UNLOCK methods. btw there is uses cases like a custom terraform http backend https://developer.hashicorp.com/terraform/language/settings/backends/http

**Comment by Jethril** [comment]
I agree, maybe a `Custom(String)` enum member could be added on the `HttpMethod`?
