### ISSUE TITLE
Add more `block helpers` to the `hbs` template example

### ISSUE THREAD

**Issue by Luni-4** [rwf2/Rocket#2600]
**Is your feature request motivated by a concrete problem? Please describe.**

The `hbs` template example shows a nice overview of `HandleBars` blocks, but it might also help, for new Rocket's user like me, the addition of all [block helpers](https://handlebarsjs.com/guide/block-helpers.html#block-helpers) in the example itself. Thanks in advance!

**Ideal Solution**

Extend the current `index.html.hbs` file in order to support all block helpers

**Comment by SergioBenitez** [comment]
A block helper is just a helper in `handlebars`. We already implement a helper in the example. How to make it a block helper (and any specific handlebars information) is relegated to the handlebars docs. Here's the relevant info: https://docs.rs/handlebars/latest/handlebars/trait.HelperDef.html#define-block-helper.

Happy to have the example improved, but I don't think keeping this request open as an issue is necessary.
