### ISSUE TITLE
Path to `contrib` repositories is not correct in sub `Cargo.toml` files

### ISSUE THREAD

**Issue by jeertmans** [rwf2/Rocket#2646]
**Description**

GitHub does not allow linking to a subdirectory without prepending `/tree/<branch_or_tag>` before the relative path. Currently, all (?) contrib packages have an invalid repository path, which turns into a `Page not fond` error when clicked from crates.io or docs.rs.

**To Reproduce**

See this link, for example: https://github.com/SergioBenitez/Rocket/contrib/db_pools.

**Expected Behavior**

A working link to the top folder, or the correct sub folder.

**Additional Context**

A quick fix might be to prepend `/tree/master` in all `Cargo.toml` files from the `contrib` folder.

**Comment by mathew-horner** [comment]
> Currently, all (?) contrib packages have an invalid repository path.

Looks like only these ones have an invalid path:
- `rocket_db_pools`
- `rocket_db_pools_codegen`
- `rocket_sync_db_pools_codegen`

Other ones seem fine.
