### ISSUE TITLE
Getting several lints on a #[derive(FromForm)]

### ISSUE THREAD

**Issue by lyssieth** [rwf2/Rocket#2655]
**Description**

I generally have both `clippy::pedantic` and `clippy::nursery` set to warn, and trying to derive FromForm on a type gives several warnings from that.

The specific lints are:
- `clippy::no_effect_underscore_binding` (from pedantic)
- `clippy::option_if_let_else` (from nursery)

**To Reproduce**

The following code can be used with the latest version of rocket on a fresh `cargo init`.
```rs
#![warn(clippy::nursery, clippy::pedantic)]

use rocket::FromForm;

#[derive(Debug, Clone, FromForm)]
pub struct Authentication {
    #[field(name = "u", validate = len(1..))]
    pub username: String,
    #[field(name = "p")]
    pub password: Option<String>,
    #[field(name = "c")]
    pub client_name: String,
}
```

**Expected Behavior**

No unrelated lints to appear from within a proc_macro derive.

**Environment:**

 - OS Distribution and Kernel: Arch Linux, kernel 6.6.2
 - Rocket Version: 0.5.0

**Comment by richo** [comment]
I believe I'm running into the same issue where rustc reports that I don't have a Debug implementation on a struct which does derive Debug.

This is my minimised testcase:

```rust
#![deny(missing_debug_implementations)]
use rocket::form::FromForm;
#[derive(Debug, FromForm)]
pub struct UpdateForm {
    name: String,
}
```

which fails to compile
