### ISSUE TITLE
Can't make private cookie not secure

### ISSUE THREAD

**Issue by BastiaanOlij** [rwf2/Rocket#2663]
**Description**

We maintain one private cookie in our system, we are running our local development environment in normal http, in production everything off course is SSL. In development this cookie is marked as not secure (`.secure(false)`). This worked fine in 0.4, but in 0.5 this seems to be ignored and the cookie is always marked as secure on the browser side.

**To Reproduce**

Add a cookie to our request:
```
request
  .cookies()
  .add_private(Cookie::build("test","1234").secure(false).into())
```

Note that from what I can tell, the cookie itself is correctly created. It is when it is added as a private cookie, the setting is ignored.

Could be related/caused by https://github.com/rwf2/Rocket/issues/2425 ?

**Expected Behavior**

I'm expecting the cookie to not be marked secure.

**Environment:**

 - OS Distribution and Kernel: macOS 10.14.6
 - Rocket Version: 0.5.0 rc4 (will test on 0.5.0 stable)

**Additional Context**

This for us is only an issue in development as we're not running SSL certificates when developing as everything is kept local to a development machine. We can probably work around this, but it does seem like undefined behaviour that the setting is being ignored.

If `add_private` now overrides this setting, possibly the internals of cookie can be changed so `secure` is internally defined as an `Option<Bool>`. Outwardly `secure` and `set_secure` can work as they are but internally this variable defaults to `None`. Setting it just wraps it in a `Some`, getting it does a `unwrap_or(default_secure)`, where `default_secure` by standard is false, but `add_private` sets it to true.

**Comment by SergioBenitez** [comment]
I can't replicate this. Setting `secure` to `false`

**Comment by BastiaanOlij** [comment]
Very strange, I wonder if this is something that is being overruled on the browser side. I'm using chrome and looking at the cookie there it is set to secure. Could this be cause the cookie was created as secure at some point and the browser hangs on to that?

I'm currently not behind the system of the client but as soon as I can do some more testing (and also test with the 0.5.0 release) hopefully I can give some better feedback.

**Comment by SergioBenitez** [comment]
Perhaps! You should look at the response being sent by the server to confirm.

**Comment by SergioBenitez** [comment]
I'm going to close this out - it does not appear that this is a bug. Please let me know if you're able to confirm otherwise!
