### ISSUE TITLE
Hello world example compiler error: macro-expanded `macro_export`

### ISSUE THREAD

**Issue by nmacholl** [rwf2/Rocket#2679]
### Rocket Version

0.5.0

### Operating System

macOS

### Rust Toolchain Version

1.74.1

### What happened?

The simple example in shown in `README.md` is not compiling for me due to a compiler error.
```
error: macro-expanded `macro_export` macros from the current crate cannot be referred to by absolute paths
```

This issue is still present on `master`. My project is part of a workspace; not sure if that is relevant.

### Test Case

```rust
#[macro_use]
extern crate rocket;

#[get("/<name>/<age>")]
fn hello(name: &str, age: u8) -> String {
    format!("Hello, {} year old named {}!", age, name)
}

#[launch]
fn rocket() -> _ {
    rocket::build().mount("/hello", routes![hello])
}
```

### Log Output

```shell
error: macro-expanded `macro_export` macros from the current crate cannot be referred to by absolute paths
 --> test/src/main.rs:5:4
  |
5 | fn hello(name: &str, age: u8) -> String {
  |    ^^^^^
  |
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
  = note: for more information, see issue #52234 <https://github.com/rust-lang/rust/issues/52234>
note: the macro is defined here
 --> test/src/main.rs:4:1
  |
4 | #[get("/<name>/<age>")]
  | ^^^^^^^^^^^^^^^^^^^^^^^
  = note: `#[deny(macro_expanded_macro_exports_accessed_by_absolute_paths)]` on by default
  = note: this error originates in the attribute macro `get` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### System Checks

- [X] My bug report relates to functionality.
- [X] I have tested against the latest Rocket release or a recent git commit.
- [X] I have tested against the latest stable `rustc` toolchain.
- [X] I was unable to find this issue previously reported.

**Comment by SergioBenitez** [comment]
Can you show your complete log output? The general crux of the issue can't possibly be true: the CI on macOS just ran all examples on stable without issue: https://github.com/rwf2/Rocket/actions/runs/7269156190/job/19806331445.

**Comment by nmacholl** [comment]
I experimented with this a bit as a "fresh" project was able to compile successfully.
The issue ultimately seemed to be caused by an unspecified `edition` in the workspace package.

The following workspace `Cargo.toml` would compile.
```
[package]
name = "foo"
edition = "2021"
rust-version.workspace = true
version.workspace = true

[dependencies]
rocket = { workspace = true }
```

However, removing the `edition` key would cause the above compiler error. I will close this issue, as it seems to be a misconfiguration of the workspace. 🙏
