### ISSUE TITLE
Improvements for the web serach: Content-Type, text/plain

### ISSUE THREAD

**Issue by szabgab** [rwf2/Rocket#2681]
### What kind of documentation problem are you reporting?

Technical Problem

### Where is the issue found?

https://rocket.rs/v0.5/guide/

### What's wrong?

It would be nice if one could also find phrases like `content-type`  (found 0) `application/json` ,  `text/plain` , `text/html` etc.  when searching on https://rocket.rs/v0.5/guide/  and if they got highlighted as other search terms do.

### System Checks

- [X] I confirmed that the issue still exists on `master` on GitHub.
- [X] I was unable to find a previous report of this problem.

**Comment by SergioBenitez** [comment]
Agreed! Quite odd. Let's definitely make this work.

**Comment by szabgab** [comment]
Searching for `RawHtml` does not return anything either, despite appearing in the docs.

**Comment by szabgab** [comment]
Very nice. Thank you!
