### ISSUE TITLE
Recognise source maps in `ContentType::from_extension`

### ISSUE THREAD

**Issue by Artemis21** [rwf2/Rocket#2685]
### What's missing?

`ContentType::from_extension` does not recognise the `.map` file extension, which is often used for JSON sourcemaps.

### Ideal Solution

```rust
assert_eq!(ContentType::from_extension("map").unwrap(), ContentType::JSON)
```

### Why can't this be implemented outside of Rocket?

It can be easily implemented outside of Rocket, see workarounds below.

However, the same could be said of any other file extension that `ContentType::from_extension` recognises. It would nevertheless add to the utility of the function to include this additional, frequently used file type, and should not be excessively burdensome to add or maintain.

### Are there workarounds usable today?

A workaround is trivial:

```rust
fn my_from_extension(ext: &str) -> _ {
    if ext == "map" {
        Ok(ContentType::JSON)
    else {
        ContentType::from_extension(ext)
    }
}
```

### Alternative Solutions

`.map` is generally used in addition to the file extension that it is a sourcemap for, it might make sense to only recognise `.css.map` and `.js.map` (and perhaps some others?).

### Additional Context

Source maps are files used to make minified code more easily debugged, by linking the un-minified source. They are automatically emitted by web bundlers and frequently used in web development.

### System Checks

- [X] I do not believe that this feature can or should be implemented outside of Rocket.
- [X] I was unable to find a previous request for this feature.

**Comment by SergioBenitez** [comment]
Is this MIME type registered with IANA? Please point me to the registration or other canonical source for the expected content-type of `.map` files.

**Comment by Artemis21** [comment]
I have nothing, it seems to be only conventional.
