### ISSUE TITLE
Link to GitHub discussion from the web site

### ISSUE THREAD

**Issue by szabgab** [rwf2/Rocket#2692]
### API Docs to Existing Functionality

https://rocket.rs/

### Problems with Existing Functionality

It took me quite a while till I figured out (I hope correctly) that the recommended place to ask question is the discussion in GitHub. 

### Suggested Changes

It might be a good idea to add a menu entry to the top of the web site called "Community" or "Help"  either linking directly to https://github.com/rwf2/Rocket/discussions or showing some explanation on how to get help and where to ask questions linking to the various forums.

### Alternatives Considered

na

### System Checks

- [X] I do not believe that this suggestion can or should be implemented outside of Rocket.

- [X] I was unable to find a previous suggestion for this change.

**Comment by Siddharth1605** [comment]
I'd like to work on this issue

**Comment by Siddharth1605** [comment]
As mentioned by @szabgab , it is a good idea to add a menu entry to the top of the website, labeled either 'Community' or 'Help,' that directs users to https://github.com/rwf2/Rocket/discussions. But the website already contains this information in the guide section under #Getting Help, so I have added the discussion link there. Maintainers, please review this pull request, and inform me of any necessary updates.
