### ISSUE TITLE
Inject script to auto-reload browser when Rocket restarts

### ISSUE THREAD

**Issue by rikhuijzer** [rwf2/Rocket#2728]
### What's missing?

First of all, thanks for making Rocket. I like it a lot.

I would like to open a feature request. Whenever I change my templates or Rocket code, Rocket restarts automatically with
```sh
cargo watch -x run
```
as described in https://github.com/rwf2/Rocket/issues/292#issuecomment-730392516. However, my browser doesn't automatically refresh the page meaning that I manually have to refresh it upon each change.

### Ideal Solution

The ideal solution would be something like what is used in the `npm` `live-server` package. There, some Javascript is injected which connects to an open socket. Whenever the server reloads some files, the browser receives a notification and reloads the page.

### Why can't this be implemented outside of Rocket?

I wouldn't know how to implement this outside of Rocket. 

### Are there workarounds usable today?

Yes. One workaround that works reasonably well for me is to inject the following Javascript into my HTML pages when in development mode:
```javascript
<script>
  function check_reload() {
      fetch("/check_reload").then(response => response.text()).then(data => {
          if (data === "true") {
              location.reload();
          }
      });
  }
  setInterval(check_reload, 2000);
</script>
```
and to add the following endpoint to my Rocket server:
```rust
lazy_static! {
    static ref SHOULD_RELOAD: Mutex<bool> = Mutex::new(true);
}

#[get("/check_reload")]
async fn check_reload() -> String {
    let mut should_reload = SHOULD_RELOAD.lock().unwrap();
    if *should_reload {
        *should_reload = false;
        return "true".to_string();
    } else {
        return "false".to_string();
    }
}
```
So, what happens here is that the browser asks Rocket ever 2 seconds whether the browser should reload. If Rocket just reloaded, the answer is `true`. If Rocket has been asked this before but didn't restart, then the answer is `false`.

There are some drawbacks to this approach though:
1. I have to set `log_level = "critical"` in `Rocket.toml` to avoid seeing one request pop up every 2 seconds (this would not happen with a socket).
1. The browser "network" inspection tools are full of requests (this would not happen with a socket).
1. There is a delay of 2 seconds before the page reloads (or even more requests spamming the logs).
1. I'm not using templates currently, but I think my logic will not work correctly there.

### Alternative Solutions

Ideally, something would wrap around Rocket which keeps track of changes and keeps a socket open. Whenever Rocket then changes, it would notify the browser. I guess this could be something like nginx but then with some logic to track whether Rocket changed.

### System Checks

- [X] I do not believe that this feature can or should be implemented outside of Rocket.
- [X] I was unable to find a previous request for this feature.

**Comment by the10thWiz** [comment]
This is more difficult than you might think. I'm not sure how npm's live-server works, but I suspect it's unloading and reloading the server, but keeping any existing steaming connections alive. For Rocket, because we aren't an interpreted language, when Rocket is restarted, the OS automatically resets every connection, so sockets would be disconnected in this case.

I think this could be implemented outside of Rocket, but it would require forking cargo watch to make it work. The idea is that it would open a Websocket Server on a different port (say 8001), and the client script would force reload the page when asked by the server. Injecting the client script automatically likely isn't worth the effort, especially since we don't know what each page is used for. I would suggest simply asking the users to inject it by hand, but a more automated solution might be possible via the webdriver spec.

**Comment by RuboGubo** [comment]
From what I can think of what you would would be to create a faring that inserts into the html some js that listens on a server sent event, then once the fairing shuts down, it tells the js to start polling the server, once the js recives a response from one of it's polls, it would reload the page and start over.

I'll try to make a crate for it when I get a change!

**Comment by SergioBenitez** [comment]
I believe this can be implemented entirely outside of Rocket. Should such a crate be written and be proven to be reliable enough, we can certainly consider bringing it in to `contrib`.

The trickiest part is to reliably inject some javascript to all outgoing requests. Here's some code I wrote for another project that does this as a `Fairing`:

```rust
//! Copyright (c) 2016 Sergio Benitez
//! The MIT License (MIT)
//!
//! Copyright 2016 Sergio Benitez
//! Apache License, Version 2.0
//!
//! You may not use this file except in compliance with one or both licenses above.

use std::pin::Pin;
use std::task::{Context, Poll};

use bytes::Buf;
use memchr::memmem;

use rocket::{Request, Response};
use rocket::fairing::{Fairing, Info, Kind};
use rocket::response::Body;

use rocket::futures::ready;
use rocket::tokio::io::{AsyncRead, AsyncBufRead, ReadBuf, BufReader};

#[derive(Debug, Copy, Clone)]
pub struct Injector {
    content: &'static str,
    inject: bool,
}

pub struct InjectedBody<'r> {
    body: BufReader<Body<'r>>,
    content: std::io::Cursor<&'static [u8]>,
    state: State,
}

enum State {
    Searching,
    Injecting,
    PassThrough,
}

impl Injector {
    pub fn new(inject: bool, content: &'static str) -> Self {
        Injector { inject, content }
    }
}

#[rocket::async_trait]
impl Fairing for Injector {
    fn info(&self) -> Info {
        Info { name: "JS Injector", kind: Kind::Response }
    }

    async fn on_response<'r>(&self, _req: &'r Request<'_>, res: &mut Response<'r>) {
        if !self.inject || !res.content_type().map_or(false, |ct| ct.is_html()) {
            return;
        }

        let body = res.body_mut().take();
        res.set_streamed_body(InjectedBody {
            body: BufReader::new(body),
            content: std::io::Cursor::new(self.content.as_bytes()),
            state: State::Searching,
        })
    }
}

impl<'r> AsyncRead for InjectedBody<'r> {
    fn poll_read(
        mut self: Pin<&mut Self>,
        cx: &mut Context<'_>,
        buf: &mut ReadBuf<'_>,
    ) -> Poll<std::io::Result<()>> {
        loop {
            if buf.remaining() == 0 {
                return Poll::Ready(Ok(()));
            }

            match self.state {
                State::Searching => {
                    let mut body = Pin::new(&mut self.body);
                    let bytes = ready!(body.as_mut().poll_fill_buf(cx))?;
                    if bytes.is_empty() {
                        self.state = State::Injecting;
                        continue;
                    }

                    // TODO: Search for more closing tags using aho-corasick.
                    let n = match memmem::find(bytes, b"</body>") {
                        Some(0) => { self.state = State::Injecting; continue; }
                        Some(i) => std::cmp::min(i, buf.remaining()),
                        None => std::cmp::min(bytes.len(), buf.remaining()),
                    };

                    buf.put_slice(&bytes[..n]);
                    body.consume(n);
                    return Poll::Ready(Ok(()));
                },
                State::Injecting => {
                    if self.content.has_remaining() {
                        return Pin::new(&mut self.content).poll_read(cx, buf);
                    } else {
                        self.state = State::PassThrough;
                    }
                }
                State::PassThrough => {
                    return Pin::new(&mut self.body).poll_read(cx, buf);
                }
            }
        }
    }
}
```
