### ISSUE TITLE
Possible Incompleteness

### ISSUE THREAD

**Issue by YichiZhang0613** [rwf2/Rocket#2740]
### What kind of documentation problem are you reporting?

Technical Problem

### Where is the issue found?

https://github.com/rwf2/Rocket/blob/master/core/lib/src/form/buffer.rs

### What's wrong?

I think the code should check string.len() >= len as comments mentioned.
```rust
    /// # Panics
    ///
    /// Panics if `string.len() < len`.
    pub(crate) fn push_split<S: Into<T>>(&self, string: S, n: usize) -> (&T::Target, &T::Target) {
        let buffered = self.push(string);
        let a = &buffered[..n];
        let b = &buffered[n..];
        (a, b)
    }
```

### System Checks

- [X] I confirmed that the issue still exists on `master` on GitHub.
- [X] I was unable to find a previous report of this problem.

**Comment by SergioBenitez** [comment]
This is an internal method, and we expect to call it correctly. Anything else would be a bug.
