### ISSUE TITLE
doc: change `&ContentType` with `&Accept` in the list of implementations of `FromRequest`

### ISSUE THREAD

**Issue by quarthex** [rwf2/Rocket#2743]
Good day human beings,

It seems that the following line need to be corrected.

https://github.com/rwf2/Rocket/blob/b15dc700aa16647c10f51ee9e9a7a5bfed072fb1/core/lib/src/request/from_request.rs#L152C12-L152C23

Best regards

**Comment by SergioBenitez** [comment]
Thank you for letting us know!
