### ISSUE TITLE
Guide navigation causes relative links inside articles to 404

### ISSUE THREAD

**Issue by LostLuma** [rwf2/Rocket#2749]
### What kind of documentation problem are you reporting?

Broken Links

### Where is the issue found?

https://rocket.rs/guide/v0.5/quickstart//#quickstart

### What's wrong?

Using the left-hand navigation inside the guide adds two following slashes to the URL of the page you navigated to. This causes relative links inside that article to go to the wrong location and results in a 404 error.

To reproduce visit the [introduction](https://rocket.rs/guide/v0.5/introduction), navigate to the Quickstart page using the left-hand navigation and click on the `Getting started` link inside the article. Instead of ending up at `guide/v0.5/getting-started` you are sent to `guide/v0.5/quickstart/getting-started/`. This also affects some other pages.

### System Checks

- [X] I confirmed that the issue still exists on `master` on GitHub.
- [X] I was unable to find a previous report of this problem.

**Comment by SergioBenitez** [comment]
Thank you for reporting this! Just pushed a fix that addresses the issue. Should be live now!
