### ISSUE TITLE
Add SQLite extensions

### ISSUE THREAD

**Issue by priv2024** [rwf2/Rocket#2762]
### What's missing?

I would like to load custom extensions to an SQLite database (such as [fuzzy](https://github.com/nalgeon/sqlean/blob/main/docs/fuzzy.md) or [vsv](https://github.com/nalgeon/sqlean/blob/main/docs/vsv.md)).

SQLx currently supports it, but I could not find a way to achieve that in the framework

### Ideal Solution

In the `init` function as follow:

```rust
#[derive(Database)]
#[database("ship")]
pub struct Database(SqlitePool);

#[rocket::launch]
fn rocket() -> _ {
  rocket::build().attach(Database::init(&["trusted/sqlite/extension"]));
}
```

### Why can't this be implemented outside of Rocket?

SQLx initialization, pool and connection is managed by Rocket itself, for which we do not have a way to configure the behavior.

### Are there workarounds usable today?

I am looking for one.

### System Checks

- [X] I do not believe that this feature can or should be implemented outside of Rocket.
- [X] I was unable to find a previous request for this feature.

**Comment by SergioBenitez** [comment]
> SQLx currently supports it

Could you share the part of `sqlx`'s docs that detail this support?

**Comment by priv2024** [comment]
In `SqliteConnectionOptions`:
[https://docs.rs/sqlx/latest/sqlx/sqlite/struct.SqliteConnectOptions.html#method.extension](https://docs.rs/sqlx/latest/sqlx/sqlite/struct.SqliteConnectOptions.html#method.extension)
