### ISSUE TITLE
Middleware that handles requests for static resources

### ISSUE THREAD

**Issue by summer-boythink** [rwf2/Rocket#2763]
### What's missing?

I looked at the documentation and found that I could write `Fairings` to fulfill the requirements of `Middleware that handles requests for static resources`. I am curious if there is any built-in `Fairings` that can meet this requirement without writing by myself

### Why can't this be implemented outside of Rocket?

Can be implemented, but I would like to have it provided built-in

### System Checks

- [ ] I do not believe that this feature can or should be implemented outside of Rocket.
- [ ] I was unable to find a previous request for this feature.

**Comment by SergioBenitez** [comment]
[FileServer](https://api.rocket.rs/v0.5/rocket/fs/struct.FileServer)

**Comment by summer-boythink** [comment]
> [FileServer](https://api.rocket.rs/v0.5/rocket/fs/struct.FileServer)
thanks you
