### ISSUE TITLE
Can't change IP that Rocket starts from.

### ISSUE THREAD

**Issue by s4Dt0y** [rwf2/Rocket#2775]
### Rocket Version

0.5.0

### Operating System

macOS 14.4.1

### Rust Toolchain Version

rustc 1.79.0-nightly (9d79cd5f7 2024-04-05)

### What happened?

I am trying to change the ip address that rocket hosts on from 127.0.0.1 to 0.0.0.0 so that I can reach the server from a different computer. However

### Test Case

```rust
#[macro_use] extern crate rocket;

#[get("/")]
fn index() -> &'static str {
    "HELLO"
}

#[launch]
fn launch() -> _ {
    rocket::build()
        .configure(Config::figment().merge(("address", "0.0.0.0")))
        .configure(Config::figment().merge(("port", 80)))
        .mount("/", routes![index])
}
```

### Log Output

```shell
-- configuration trace information --
   >> "address" parameter source: rocket::Config::default()
   >> "port" parameter source: (&str, i32)
   >> "workers" parameter source: rocket::Config::default()
   >> "max_blocking" parameter source: rocket::Config::default()
   >> "keep_alive" parameter source: rocket::Config::default()
   >> "ident" parameter source: rocket::Config::default()
   >> "ip_header" parameter source: rocket::Config::default()
   >> "limits" parameter source: rocket::Config::default()
   >> "temp_dir" parameter source: rocket::Config::default()
   >> "log_level" parameter source: `ROCKET_` environment variable(s)
   >> "shutdown" parameter source: rocket::Config::default()
   >> "cli_colors" parameter source: rocket::Config::default()
🔧 Configured for debug.
   >> address: 127.0.0.1
   >> port: 8080
   >> workers: 8
   >> max blocking threads: 512
   >> ident: Rocket
   >> IP header: X-Real-IP
   >> limits: bytes = 8KiB, data-form = 2MiB, file = 1MiB, form = 32KiB, json = 1MiB, msgpack = 1MiB, string = 8KiB
   >> temp dir: /var/folders/kb/378jxcs17d7cjsp1_5q80l1h0000gp/T/
   >> http/2: true
   >> keep-alive: 5s
   >> tls: disabled
   >> shutdown: ctrlc = true, force = true, signals = [SIGTERM], grace = 2s, mercy = 3s
   >> log level: debug
   >> cli colors: true
📬 Routes:
   >> (index) GET /
📡 Fairings:
   >> Shield (liftoff, response, singleton)
🛡️ Shield:
   >> Permissions-Policy: interest-cohort=()
   >> X-Content-Type-Options: nosniff
   >> X-Frame-Options: SAMEORIGIN
🚀 Rocket has launched from http://127.0.0.1:8080
```

### System Checks

- [x] My bug report relates to functionality.
- [X] I have tested against the latest Rocket release or a recent git commit.
- [X] I have tested against the latest stable `rustc` toolchain.
- [X] I was unable to find this issue previously reported.

**Comment by SergioBenitez** [comment]
The log does not correspond to the code you posted. Please to try post logs that correspond to the example you post.

The `configure` method _sets_ the configuration provider. In other words, the configuration provide is replaced by whatever you pass in. Thus, the second call to `configure()` undoes what the first call to `configure()` does. In your case, this means the `address` is reset to the default and only the port is maintained:

```
🔧 Configured for debug.
   >> address: 127.0.0.1
   >> port: 80
```

If you want to set both programmatically, you need to do so with a single provider:

```rust
    let figment = Config::figment().merge(("address", "0.0.0.0")).merge(("port", 80));
    rocket::custom(figment).mount("/", routes![index])
```

Note as well that you don't need to do this programmatically at all. Just set them in a `Rocket.toml` file. You probably want to do this only in the `release` profile:

```toml
[release]
address = "0.0.0.0"
port = 80
```

You can also use environment variables:

```
ROCKET_ADDRESS="0.0.0.0" ROCKET_PORT=80 cargo run
```
