### ISSUE TITLE
MiniJinja can't be used for templates

### ISSUE THREAD

**Issue by Dog2657** [rwf2/Rocket#2787]
### Rocket Version

0.5.0

### Operating System

MacOS 14.4.1

### Rust Toolchain Version

rustc 1.77.2 (25ef9e3d8 2024-04-09)

### What happened?

I am trying to intergrate MiniJinja.

## Cargo.toml
```[package]
name = "***********"
version = "0.1.0"
edition = "2021"



[dependencies]
rocket = "0.5.0"
minijinja = { features = ["loader"],version = "1.0.20" }
once_cell = "1.13.1"
dotenvy = "0.15.7"

[dependencies.rocket_dyn_templates]
version = "0.1.0"
features = ["handlebars", "tera", "minijinja"]
```

### Test Case

```rust
#[macro_use] extern crate rocket;

use rocket::fs::{FileServer, relative};

use rocket_dyn_templates::{Template, context};

#[get("/")]
fn test() -> Template {
    Template::render("pages/signup", context! { text: "Welcome to the World Wide Web" })
}


#[launch]
fn rocket() -> _ {
    rocket::build()
        .attach(Template::fairing())
        .mount("/", routes![test])
}
```

### Log Output

```shell
ailed to select a version for `rocket_dyn_templates`.
    ... required by package `****** v0.1.0 (/Users/dog2657/Coding Projects/Stacks/******/*****/app)`
versions that meet the requirements `^0.1.0` (locked to 0.1.0) are: 0.1.0

the package `*******` depends on `rocket_dyn_templates`, with features: `minijinja` but `rocket_dyn_templates` does not have these features.


failed to select a version for `rocket_dyn_templates` which could resolve this conflict
```

### Additional Context

I encountered this error by following this [guide](https://api.rocket.rs/master/rocket_dyn_templates/#configuration)

### System Checks

- [X] My bug report relates to functionality.
- [X] I have tested against the latest Rocket release or a recent git commit.
- [X] I have tested against the latest stable `rustc` toolchain.
- [X] I was unable to find this issue previously reported.

**Comment by SergioBenitez** [comment]
The guide you're reading is for the `master` branch (see the `master` part of the URL). Version 0.5 does not yet include support for minijnja, but `master` does. If you want to use minijinja now, depend on `rocket` using `git` (https://rocket.rs/guide/master/getting-started/#hello-world).
