### ISSUE TITLE
New release of rocket_dyn_templates

### ISSUE THREAD

**Issue by senekor** [rwf2/Rocket#2793]
### Rocket Version

0.5.0

### Operating System

Linux

### Rust Toolchain Version

stable

### What happened?

The official Rust website would like to update their handlebars dependency. The change was [merged in January](https://github.com/rwf2/Rocket/pull/2700) but there hasn't been a new release since November. Please cut a new release.

### Test Case

```rust
.
```

### Log Output

```shell
.
```

### System Checks

- [X] My bug report relates to functionality.
- [X] I have tested against the latest Rocket release or a recent git commit.
- [X] I have tested against the latest stable `rustc` toolchain.
- [X] I was unable to find this issue previously reported.

**Comment by SergioBenitez** [comment]
Will get a new release out shortly.

**Comment by SergioBenitez** [comment]
Released!

**Comment by senekor** [comment]
Thank you! :slightly_smiling_face:
