### ISSUE TITLE
Possible error in the Json guard

### ISSUE THREAD

**Issue by cdvv7788** [rwf2/Rocket#2802]
### Rocket Version

0.5.1

### Operating System

macOS 14.5

### Rust Toolchain Version

1.76.0

### What happened?

Passing an invalid Json returns an unexpected response.
When I pass an invalid Json (not `well-formed`) the response should complain about the malformed syntax, however it returns:
```
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="color-scheme" content="light dark">
	<title>422 Unprocessable Entity</title>
</head>

<body align="center">
	<div role="main" align="center">
		<h1>422: Unprocessable Entity</h1>
		<p>The request was well-formed but was unable to be followed due to semantic errors.</p>
		<hr />
	</div>
	<div role="contentinfo" align="center">
		<small>Rocket</small>
	</div>
</body>

</html>
```

This errors seems incorrect. The json is not valid, so it should not be `well-formed`.

### Test Case

```rust
#[macro_use]
extern crate rocket;
use rocket::serde::{json::Json, Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize)]
#[serde(crate = "rocket::serde")]
struct Credentials<'r> {
    email: &'r str,
    password: &'r str,
}

#[post("/", format = "json", data = "<input>")]
fn index(input: Json<Credentials<'_>>) -> Json<Credentials> {
    Json(input.into_inner())
}

#[launch]
fn rocket() -> _ {
    rocket::build().mount("/", routes![index])
}

#[launch]
fn rocket() -> _ {
    rocket::build().mount("/", routes![index])
}

#[cfg(test)]
mod test {
    use rocket::http::ContentType;
    // Using the preferred `blocking` API.
    #[test]
    fn test_hello_world_blocking() {
        use rocket::local::blocking::Client;

        // Construct a client to use for dispatching requests.
        let client = Client::tracked(super::rocket()).expect("valid `Rocket`");

        // Dispatch a request to 'GET /' and validate the response.
        let data = r#"{"email": "test", 
        "password": 1
        obviously invalid json
        }"#;
        let response = client
            .post("/")
            .header(ContentType::JSON)
            .body(data)
            .dispatch();
        assert!(response.into_string().unwrap().contains("syntax"));
    }
}
```

### Log Output

```shell
❯ ROCKET_LOG_LEVEL=debug cargo test
   Compiling ticket-computer v0.1.0 (/Users/cristian/projects/personal/ticket-computer)
    Finished test [unoptimized + debuginfo] target(s) in 0.47s
     Running unittests src/main.rs (target/debug/deps/ticket_computer-05198c8dd26906d8)

running 1 test
test test::test_hello_world_blocking ... FAILED

failures:

---- test::test_hello_world_blocking stdout ----
-- configuration trace information --
   >> "address" parameter source: rocket::Config::default()
   >> "port" parameter source: rocket::Config::default()
   >> "workers" parameter source: rocket::Config::default()
   >> "max_blocking" parameter source: rocket::Config::default()
   >> "keep_alive" parameter source: rocket::Config::default()
   >> "ident" parameter source: rocket::Config::default()
   >> "ip_header" parameter source: rocket::Config::default()
   >> "limits" parameter source: rocket::Config::default()
   >> "temp_dir" parameter source: rocket::Config::default()
   >> "log_level" parameter source: `ROCKET_` environment variable(s)
   >> "shutdown" parameter source: rocket::Config::default()
   >> "cli_colors" parameter source: rocket::Config::default()
🔧 Configured for debug.
   >> address: 127.0.0.1
   >> port: 8000
   >> workers: 10
   >> max blocking threads: 512
   >> ident: Rocket
   >> IP header: X-Real-IP
   >> limits: bytes = 8KiB, data-form = 2MiB, file = 1MiB, form = 32KiB, json = 1MiB, msgpack = 1MiB, string = 8KiB
   >> temp dir: /var/folders/pw/0x52xwv901n5bhf92_0606rc0000gn/T/
   >> http/2: true
   >> keep-alive: 5s
   >> tls: disabled
   >> shutdown: ctrlc = true, force = true, signals = [SIGTERM], grace = 2s, mercy = 3s
   >> log level: debug
   >> cli colors: true
📬 Routes:
   >> (index) POST / application/json
📡 Fairings:
   >> Shield (liftoff, response, singleton)
🛡️ Shield:
   >> X-Content-Type-Options: nosniff
   >> X-Frame-Options: SAMEORIGIN
   >> Permissions-Policy: interest-cohort=()
🚀 Rocket has launched locally
POST / application/json:
   >> Matched: (index) POST / application/json
   >> Data guard `Json < Credentials < '_ > >` failed: Parse("{\"email\": \"test\", \n        \"password\": 1\n        obviously invalid json\n        }", Error("invalid type: integer `1`, expected a borrowed string", line: 2, column: 21)).
   >> Outcome: Error(422 Unprocessable Entity)
   >> No 422 catcher registered. Using Rocket default.
thread 'test::test_hello_world_blocking' panicked at src/main.rs:43:9:
assertion failed: response.into_string().unwrap().contains("syntax")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Additional Context

The `assert` in the test case is not very useful, but the catchers are not configured when running the tests apparently.

The main issue is that it seems to try to run the type validations before making sure that the json is correct, giving out the incorrect message: `(422) The request was well-formed but was unable to be followed due to semantic errors.`. This payload contains not only semantic errors, but syntax errors too.

If I change the json input to (fixing the type of the incorrect field):
```
{"email": "test", 
        "password": "1"
        obviously invalid json
        }
```
I get the expected response: `(400) The request could not be understood by the server due to malformed syntax`.

### System Checks

- [X] My bug report relates to functionality.
- [X] I have tested against the latest Rocket release or a recent git commit.
- [X] I have tested against the latest stable `rustc` toolchain.
- [X] I was unable to find this issue previously reported.

**Comment by SergioBenitez** [comment]
The status code is derived from the `serde_json::Error` [classification](https://docs.rs/serde_json/latest/serde_json/struct.Error.html#method.classify). In this case, serde is indicating that the input data is semantically incorrect, thus we return a 422. If it should be returning something else, then that would be an issue with `serde_json`, not Rocket. I'd advise opening an issue in the `serde_json` repository if you feel that's the case.

**Comment by the10thWiz** [comment]
Actually, I think this is somewhat expected behavior of `serde_json`. It's simply failing fast, and returning the first error it finds - which happens to be the incorrect type. My assumption would be that serde_json just stops, and doesn't actually attempt to parse the obviously incorrect json.

From my perspective, the first example request actually has two issues - a data-type issue, and being mal-formed. In this sense, we could respond with either `400` OR `422`, although it may be more useful to respond with one or the other. From my perspective, I don't think it's worth the extra effort (and CPU cycles) to validate that the request contains valid JSON if we already know it isn't going to work for any other reason.

**Comment by SergioBenitez** [comment]
I think @the10thWiz's comment is right, and furthermore, there's not much we can in Rocket. As mentioned in my previous comment, this should be addressed in `serde_json`, if at all. A change there would immediately be reflected by Rocket. Given that this is not actionable, I'm closing this out.
