### ISSUE TITLE
Allow Generics in route functions

### ISSUE THREAD

**Issue by RuboGubo** [rwf2/Rocket#2812]
### What's missing?

The ability to use generics when defining functions for routes.

I personally have been trying to find ways to make it easier and faster to get from 0 to CRUD, and this is one area where rocket is still very bad. You have to write a new route for each new type which takes forever, the alternatives (creating a macro) aren't a viable alternative and certainty don't create a "quick and easy" developer experience leaving most to just copy past. Using generics is already a very "rust" thing to do, so I think it's important to make it work on the route functions as well.

I should make it clear though that this is useful beyond making CRUD apps quicker, it also allows for crates to provide implementations for your own type.

### Ideal Solution

example code
```rust
#[get("/<id>")]
async fn get<T: ManageDB + Serialize>(conn: Connection<MainDB>, id: i64) -> Json<T> {
    Json(T::from_db(id, conn).await.unwrap())
}
```
and this is how the route would be mounted
```rust
#[launch]
fn rocket() -> _ {
    rocket::build()
        .attach(MainDB::init())
        .attach(SqlxMigrator::<MainDB>::migrate())
        .mount("/user", routes![get::<User>])
}
```

### Why can't this be implemented outside of Rocket?

Part of the core engine

### Are there workarounds usable today?

make your own macro

### System Checks

- [X] I do not believe that this feature can or should be implemented outside of Rocket.
- [X] I was unable to find a previous request for this feature.

**Comment by SergioBenitez** [comment]
See #408.
