### ISSUE TITLE
Caching a background image with the `Cache-Control` header

### ISSUE THREAD

**Issue by nonk123** [rwf2/Rocket#2815]
Sounds simple enough: return a `NamedFile` from a handler whlist setting the `Cache-Control` header to e.g. `max-age=86400`. Still, I can't seem to figure this out no matter how much I look into the docs.

I'm using `rocket` 0.5.1 if that matters.

My questions:

- Is there no built-in way to "just do" this? Setting a caching policy for an image must be a common operation, especially for `FileServer` and alike.
- Do I really need to implement a custom `Responder` whenever I need to add/change a response header? It's the closest I've actually gotten to solving this, but it never worked in the end since it needed `async` in order to respond from a `NamedFile`.

**Comment by the10thWiz** [comment]
> Is there no built-in way to "just do" this?

Not yet. This is coming in 0.6, see #2789.

> since it needed async in order to respond from a NamedFile

You shouldn't need async in `Responder` to respond with a `NamedFile`. Something like the following should work:

```rust
pub struct CacheControl<R>(Duration, R);
impl<'r, 'o: 'r, R: Responder<'r, 'o>> Responder<'r, 'o> for CacheControl<R> {
    fn respond_to(self, req: &'r Request<'_>) -> Result<'o> {
        Response::build_from(self.1.respond_to(req)?)
            .header_adjoin(Header::new("Cache-Control", format!("max-age={}", self.0.as_secs())))
            .ok()
    }
}
```

**Comment by nonk123** [comment]
Thanks for the explanation! I'm currently using my reverse-proxy for adding the `Cache-Control` header, and it works great; but this feature would be really useful to have inside Rocket natively! Looking forward to 0.6.
