### ISSUE TITLE
No way to turn off coloured log output

### ISSUE THREAD

**Issue by ijackson** [rwf2/Rocket#2824]
### Rocket Version

0.5.1

### Operating System

Linux with xterm

### Rust Toolchain Version

rustc 1.79.0 (129f3b996 2024-06-10)

### What happened?

When I run Rocket, it prints a pile of stuff to the terminal.  However, I cannot read it, because of the colouring.  (I have anomalous colour vision, "colourblindness" if you want to be imprecise.)

There is no (documented?) way to turn the colouring off.

Also, it doesn't honour TERM.  This means that when I run Rocket inside my Emacs M-x compile mode window, I see a bunch of escape sequences.

This is very frustrating.  IMO if it is too hard to make colouration configurable, it should be simply turned off.

I infer from reading various tickets eg maybe #2536 #2324 that `tracing` is involved.  The interaction of Rocket with `tracing` ought to be documented, too.  For now maybe bodging it with `env_logger` will make me able to make progress?

### Test Case

```rust
#[rocket::main]
async fn main() -> anyhow::Result<()> {
    rocket::build().launch().await?;

    Ok(())
}
```

### Log Output

```shell
🔧 Configured for debug.
   >> address: 127.0.0.1
   >> port: 8000
   >> workers: 8
   >> max blocking threads: 512
   >> ident: Rocket
   >> IP header: X-Real-IP
   >> limits: bytes = 8KiB, data-form = 2MiB, file = 1MiB, form = 32KiB, json = 1MiB, msgpack = 1MiB, string = 8KiB
   >> temp dir: /tmp
   >> http/2: true
   >> keep-alive: 5s
   >> tls: disabled
   >> shutdown: ctrlc = true, force = true, signals = [SIGTERM], grace = 2s, mercy = 3s
   >> log level: normal
   >> cli colors: true
📡 Fairings:
   >> Shield (liftoff, response, singleton)
🛡️ Shield:
   >> X-Frame-Options: SAMEORIGIN
   >> X-Content-Type-Options: nosniff
   >> Permissions-Policy: interest-cohort=()
🚀 Rocket has launched from http://127.0.0.1:8000
^CWarning: Received SIGINT. Requesting shutdown.
```

### System Checks

- [X] My bug report relates to functionality.
- [X] I have tested against the latest Rocket release or a recent git commit.
- [X] I have tested against the latest stable `rustc` toolchain.
- [X] I was unable to find this issue previously reported.

**Comment by SergioBenitez** [comment]
You can turn off colors via the cli_colors setting. This is documented in various places including the [configuration guide](https://rocket.rs/guide/v0.5/configuration/#overview) and at the tail of the [getting started guide](https://rocket.rs/guide/v0.5/getting-started/) as well as the API docs. By default, you can just set `ROCKET_CLI_COLORS=0` to disable colors.

**Comment by ijackson** [comment]
Oh!  I don't know why I didn't see that in the configuration guide.  I did look there.  Maybe I only searched for the UK spelling?  I did search the API docs for "log" but it's under "cli" so I didn't find it that way.

Sorry for the noise.
