### ISSUE TITLE
Implement derive FromParam for enum

### ISSUE THREAD

**Issue by loikki** [rwf2/Rocket#2826]
### API Docs to Existing Functionality

https://api.rocket.rs/v0.5/rocket/request/trait.FromParam

### Problems with Existing Functionality

It seems that FromParam is not implemented as a derive macro for enum. It means that you cannot receive an enum as a path variable.

Implementing it for any enum would not make any sense but why not providing it for enum without internal data (so kind of a string enum based on the variable name).

I can implement it if you are interested.

### Suggested Changes

Simply, we can declare an enum with a derive instruction and then add it as an option in a given route. When we query the endpoint, we can simply send the String corresponding to the enum.

```rust
#[derive(Debug, FromParamEnum)]
pub enum MyEnum {
  Option1,
  Option2
}

#[get("/<option>")]
pub async fn get_option(
    option: MyEnum,
)  {
  println!("{:?}", option);
}

// Query: GET /Option1
```

It requires a relatively simple code to do so:

```rust
extern crate proc_macro;
use proc_macro::TokenStream;
use quote::quote;
use syn::{parse_macro_input, Data, DeriveInput};

// Example of expansion
// impl<'a> FromParam<'a> for MyEnum {
//     type Error = &'a str;

//     fn from_param(param: &'a str) -> Result<Self, Self::Error> {
//         match param {
//             "Option1" => Ok(MyEnum::Option1),
//             "Option2" => Ok(MyEnum::Option2),
//             _ => Err("Failed to find enum"),
//         }
//     }
// }

#[proc_macro_derive(FromParamEnum)]
pub fn derive_macro_param(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    let name = input.ident;

    let mut matches = quote!();

    match input.data {
        Data::Enum(ref data) => {
            for field in data.variants.iter() {
                let field_name = &field.ident;
                matches.extend(quote!(
                    stringify!(#field_name) => Ok(#name::#field_name),
                ))
            }
        }
        _ => panic!("Work only on enums"),
    };

    let expanded = quote! {
        impl<'a> FromParam<'a> for #name {
            type Error = &'a str;

            fn from_param(param: &'a str) -> Result<Self, Self::Error> {
                match param {
                    #matches
                    _ => Err("Failed to find enum")
                }
            }
        }
    };

    proc_macro::TokenStream::from(expanded)
}
```

### Alternatives Considered

The only alternative I found was to write it myself in my crate.

### System Checks

- [X] I do not believe that this suggestion can or should be implemented outside of Rocket.

- [X] I was unable to find a previous suggestion for this change.

**Comment by the10thWiz** [comment]
I think this is a logical addition to Rocket. The derive should probably just be called `FromParam`, and could (later) be enhanced with support for certain kinds of structs (e.g. a struct with a single field could just call from param on the field).

I can't say for sure it will be accepted, but I think there's a high likelihood.
