### ISSUE TITLE
Expose the `tracing` layer construction to allow you to add other e.g. tracing_subscribers

### ISSUE THREAD

**Issue by v3xro** [rwf2/Rocket#2840]
### What's missing?

In the recently added `RocketDynFmt` the `tracing_subscriber` is fully constructed inside Rocket. This makes it not possible to add other layers (e.g. https://github.com/tokio-rs/console) to the application without changing Rocket's source code.

### Ideal Solution

There should either be a fairing where you can register layers, or the `RocketDynFmt` implementation could be exposed further as a trait you could implement in your application (with suitable defaults for workers, colors, level etc.)

### Why can't this be implemented outside of Rocket?

The function where the tracing_subscriber is initialized is internal to `RocketDynFmt`.

### Are there workarounds usable today?

Other than modifying the Rocket source, no.

### System Checks

- [X] I do not believe that this feature can or should be implemented outside of Rocket.
- [X] I was unable to find a previous request for this feature.

**Comment by SergioBenitez** [comment]
[`RocketDynFmt`](https://api.rocket.rs/master/rocket/trace/subscriber/struct.RocketDynFmt) implements `From<RocketFmt<T>>`, and both it and [`RocketFmt<T>`](https://api.rocket.rs/master/rocket/trace/subscriber/struct.RocketFmt) implement `Layer` for composition with other `LookupSpan`-requiring layers/subscribers. In particular, this includes the [`Registry`](https://docs.rs/tracing-subscriber/0.3.18/tracing_subscriber/registry/index.html), so you can do something like:

```rust
use rocket::trace::subscriber::{RocketFmt, Compact};

let console_layer = console_subscriber::spawn();
let rocket_layer: RocketFmt<Compact> = RocketFmt::new(workers, cli_colors, level);

Registry::default()
    .with(console_layer)
    .with(rocket_layer)
    .try_init();
```

We could add a `RocketDynFmt::new()` which exactly emulates what happens inside of `init()` to decrease the amount of code that's needed, however. I'll do that now.

**Comment by v3xro** [comment]
Apologies, looks like I missed the impl of Layer - thanks for the example!
