### ISSUE TITLE
Implement `PartialEq` for `http::Status` with derive macro

### ISSUE THREAD

**Issue by frondeus** [rwf2/Rocket#2844]
### API Docs to Existing Functionality

https://api.rocket.rs/v0.5/rocket/http/struct.Status

### Problems with Existing Functionality

Status does not implement `PartialEq` via `derive(PartialEq)`, which causes it to lack `StructuralPartialEq`.

It prohibits using status in match:

```rs
match status {
    Status::Unauthorized => { ... },
    Status::NotFound => { ... },
    _ => { ... }
}
```

because `Status::Unauthorized` is a constant which triggers error:

```
error: to use a constant of type `rocket::http::Status` in a pattern, `rocket::http::Status` must be annotated with `#[derive(PartialEq)]`
  --> my_project/src/errors.rs:40:13
   |
40 |             Status::Unauthorized => { ... },
   |             ^^^^^^^^^^^^^^^^^^^^
   |
   = note: the traits must be derived, manual `impl`s are not sufficient
   = note: see https://doc.rust-lang.org/stable/std/marker/trait.StructuralPartialEq.html for details
``` 

### Suggested Changes

I've looked at current implementation of `PartialEq` for `Status`:
https://github.com/rwf2/Rocket/blob/1a3ef5b23fdf4a4619fa9b5d3f24cff6f8008085/core/http/src/status.rs#L363C1-L367C2

And it seems that there is nothing prohibiting automatic derive. 

### Alternatives Considered

An alternative solution to my `match` expression is something like this:

```rs
match status {
    status if status == Status::Unauthorized => { ... },
    status if status == Status::TooManyRequests => { ... },
}
```

But it doesn't feel idiomatic. 

Another would be to use code directly:

```rs
match status.code {
    401 => { ... },
    429 => { ... }
}
```

But here I'm more prone to the typo than using existing constant.

### System Checks

- [X] I do not believe that this suggestion can or should be implemented outside of Rocket.

- [X] I was unable to find a previous suggestion for this change.

**Comment by the10thWiz** [comment]
As an addendum, we should also derive `Eq`, `PartialOrd` and `Ord`, for the same reason.

**Comment by frondeus** [comment]
I'm eager to do the PR, should I also include `Hash`? It also seems to be a good candidate for derive.

**Comment by the10thWiz** [comment]
Yeah, might as well.
