### ISSUE TITLE
A new warning on rust beta: unreachable pattern

### ISSUE THREAD

**Issue by komar007** [rwf2/Rocket#2864]
### Rocket Version

0.5.1

### Operating System

Ubuntu 22.04.4

### Rust Toolchain Version

1.82.0-beta.3

### What happened?

Just letting you know of a potential problem coming. I have a CI running my code at work on beta rust, clippy, fmt, etc and recently there's been a new warning when using `rocket_ws::WebSocket`. It seems it could originate somewhere in rocket's macro:

```
warning: unreachable pattern
 --> src/main.rs:5:9
  |
5 |     ws: rocket_ws::WebSocket,
  |         ^^^^^^^^^ matches no values because `(rocket::http::Status, Infallible)` is uninhabited
  |
  = note: to learn more about uninhabited types, see https://doc.rust-lang.org/nomicon/exotic-sizes.html#empty-types
  = note: `#[warn(unreachable_patterns)]` on by default

```
Below is a somewhat minimal reproduction code.

### Test Case

```rust
use rocket::{get, response::status::NotFound};

#[get("/endpoint")]
pub async fn endpoint(
    ws: rocket_ws::WebSocket,
) -> Result<rocket_ws::Channel<'static>, NotFound<()>> {
    Ok(ws.channel(|_| Box::pin(async { Ok(()) })))
}

fn main() {}
```

### Log Output

```shell
warning: unreachable pattern
 --> src/main.rs:5:9
  |
5 |     ws: rocket_ws::WebSocket,
  |         ^^^^^^^^^ matches no values because `(rocket::http::Status, Infallible)` is uninhabited
  |
  = note: to learn more about uninhabited types, see https://doc.rust-lang.org/nomicon/exotic-sizes.html#empty-types
  = note: `#[warn(unreachable_patterns)]` on by default
```

### System Checks

- [X] My bug report relates to functionality.
- [X] I have tested against the latest Rocket release or a recent git commit.
- [X] I have tested against the latest stable `rustc` toolchain.
- [X] I was unable to find this issue previously reported.

**Comment by mikemoore13** [comment]
#[get("/confirm/<id>/<code>")]
pub async fn confirm_registration(connection: Db, id: i64, code :&str) -> Result<rocket::response::content::RawHtml<String>, Status> {

gives :

519 | pub async fn confirm_registration(connection: Db, id: i64, code :&str) -> Result<rocket::response::content::RawHtml<String>, Status> {
    |                                                                  ^ matches no values because `Infallible` is uninhabited
    |
    = note: to learn more about uninhabited types, see https://doc.rust-lang.org/nomicon/exotic-sizes.html#empty-types

**Comment by komar007** [comment]
Indeed, no warning on 1.82.0-beta.4 anymore.

**Comment by SergioBenitez** [comment]
Looks like a false positive that's been resolved!
