### ISSUE TITLE
How should I save the Rocket logs to a file?

### ISSUE THREAD

**Issue by xdestiny110** [rwf2/Rocket#2865]
### What's missing?

I would like to output the logs from Rocket to a specific text file. I noticed that Rocket seems to use the tracing library, so I tried to handle it with the following code. 
```
#[launch]
fn rocket() -> _ {
    let temp_dir: PathBuf = Path::new(&env::temp_dir()).join("alphacore_server");
    let file_appender = tracing_appender::rolling::minutely(temp_dir, "server.log");
    let (non_blocking, _guard) = tracing_appender::non_blocking(file_appender);
    tracing_subscriber::registry()
        .with(tracing_subscriber::fmt::layer().with_writer(non_blocking))
        .init();
    rocket::build().mount("/", routes![version, login])
}
```
The result is that the output on the console has disappeared, but it has not been written to the text file. I'm not sure if I missed something in the documentation, or if there is any way to achieve my goal?

### Why can't this be implemented outside of Rocket?

I believe Rocket should support logging to a specific location.

### System Checks

- [X] I do not believe that this feature can or should be implemented outside of Rocket.
- [X] I was unable to find a previous request for this feature.

**Comment by the10thWiz** [comment]
Which version of Rocket are you using? The latest release (0.5.1) is using log, only the master branch on github is using tracing.

Other than that, you should read the documentation for log or tracing, since this issue isn't specific to Rocket.

**Comment by xdestiny110** [comment]
Thanks for you reply. When I use main branch it works.
