### ISSUE TITLE
Implement QUERY Method

### ISSUE THREAD

**Issue by hawkinsw** [rwf2/Rocket#2873]
### What's missing?

I am a _huge_ fan of Rocket and thought that I could add support for the nearly-standardized QUERY method (https://www.ietf.org/archive/id/draft-ietf-httpbis-safe-method-w-body-05.html). I have a _WIP_ PR that I will post to go along with this Feature Request. I have done my absolute best to make sure that I have followed all the proper steps.

### Ideal Solution

I believe that the ideal solution is to simply add `QUERY` in the appropriate spot in the call(s) to the `define_methods` macro. Because QUERY is not yet an RFC, there will be a few changes to the `define_methods` macro so that the documentation is generated correctly. 

### Why can't this be implemented outside of Rocket?

N/A

### Are there workarounds usable today?

N/A

### Additional Context

Again, thank you for all the work that you are doing on Rocket. I understand that the PR that I will post does not have tests and that is absolutely a requirement. However, I wanted to post early/often to see whether support for `QUERY` is something that you would consider. If it is, then I will absolutely add all the tests necessary and clean up anything else that I have done incorrectly. 

### System Checks

- [X] I do not believe that this feature can or should be implemented outside of Rocket.
- [X] I was unable to find a previous request for this feature.

**Comment by SergioBenitez** [comment]
I'm of the opinion that we need a proper RFC to implement support for a method in this manner. The QUERY method has been in draft form for 3 years with various changes in its semantics in the same time, so I'm not as certain that we'll see a proper RFC soon. I _would_ be in favor of a nice mechanism for custom methods in Rocket, which would supersede the need for this PR and others like it.

**Comment by hawkinsw** [comment]
Okay! I was just trying to help!

Will

**Comment by hawkinsw** [comment]
Didn't mean to offend!

**Comment by hawkinsw** [comment]
You did not!! I was just being sure! I would love to take a crack at adding a 

> nice mechanism for custom methods in Rocket

Would you be amenable to me opening a discussion PR for the way that we would want this implemented? Once we have a sense for how it should work, I could code it up!

If that sounds okay, then I will get right on it!

Thanks for giving me the chance to contribute!
