### ISSUE TITLE
Docs discrepancy with `FromParam`

### ISSUE THREAD

**Issue by fenhl** [rwf2/Rocket#2880]
[The `FromParam` docs](https://api.rocket.rs/master/rocket/request/trait.FromParam) say:

> If the conversion fails, the incoming request will be forwarded to the next matching route, if any.

>  Since there are no additional matching routes, this example will result in a 404 error for requests with invalid `id` values.

However, the actual behavior of such an endpoint when requested with a non-`usize` parameter is to return 422 Unprocessable Content:

```rust
#[rocket::get("/<id>")]
fn hello(id: usize) -> String {
    id.to_string()
}

#[rocket::launch]
async fn launch() -> _ {
    rocket::build()
    .mount("/", rocket::routes![
        hello,
    ])
}
```

Tested on Rocket commit 3bf9ef02d6e803fe9f753777f5a829dda6d2453d.

### Discussed in https://github.com/rwf2/Rocket/discussions/2879

**Comment by the10thWiz** [comment]
If you have some time, would you mind opening a PR to update the documentation? I believe that the actual behavior here, forwarding with `422` is the appropriate action.
