### ISSUE TITLE
dev server fails to launch

### ISSUE THREAD

**Issue by surajsharma** [rwf2/Rocket#2893]
### What kind of documentation problem are you reporting?

Unclear Docs

### Where is the issue found?

https://rocket.rs/guide/v0.5/getting-started/#getting-started

### What's wrong?

`cargo run` outputs the following on wsl2 without ever starting the dev server

```
❯ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/src`
Hello, world!

```

### System Checks

- [X] I confirmed that the issue still exists on `master` on GitHub.
- [X] I was unable to find a previous report of this problem.

**Comment by SergioBenitez** [comment]
What's the complete program that you're running? Please make sure it's exactly what's on the getting started page.

**Comment by surajsharma** [comment]
I followed the tutorial at https://rocket.rs/guide/v0.5/getting-started/#getting-started

**Comment by SergioBenitez** [comment]
The tutorial guides you to running a very specific program, which would result in different output than you've pasted here. I've asked you to provide the complete program that you're compiling and executing to see where you might have gone astray. Without it, we cannot help you.

**Comment by surajsharma** [comment]
i followed the tutorial to the letter and ended up with something other than advertised.

**Comment by szabgab** [comment]
This happened to me as well.

It took me a while to realize I made a mistake.

**Comment by surajsharma** [comment]
@szabgab use the hello example from the examples folder, i think the documentation needs an update or sth
