### ISSUE TITLE
Ability to chain Data Guards.

### ISSUE THREAD

**Issue by Carreau** [rwf2/Rocket#775]
This is a followup from IRC

## Feature Requests

It would be nice to have a way to chain data guard. 

> 1. Why you believe this feature is necessary.
> 2. A convincing use-case for this feature.

Use-case : Request that are signed with a hash of the body, typically GitHub webhook. We need to way to verify the hash is correct and still likely dispatch to custom dataGuards.

Take the following approximate example:

```rust

#[post("/", data = "<payload>")]
fn webhook_post(payload: SignedPayload<Json<Value>>) -> ... {
	...
}

impl<T:FromData> FromData for SignedPayload<T> {
    type Error = ();

    fn from_data(request: &Request, data: Data) -> data::Outcome<Self, ()> {
        let mut body = String::new();
        if let Err(_) = data.open().read_to_string(&mut body) {
            let mut hmac = Hmac::new(digest, secret.as_bytes());
            hmac.input(body.as_bytes());
            if hmac.result() != requests.headers.get_one('signature'){
				return Outcome::Failure((Status::InternalServerError, ()));
			}
        }

        // ... need a way to chain to T::from_data, but data has been consumed.
		match T::from_data(request, data) {
                Outcome::Success(val) => Outcome::Success(SignedPayload(val)),
                ...
        }
}
```

That would allow clean composition of Data Guards.

  3. Why this feature can't or shouldn't exist outside of Rocket.

Data is private, AFAICT there is no way to recreate/reuse one.
You can see that [some project](https://github.com/aergonaut/railgun/) are basically implementing [this kind of DataGuard](https://github.com/aergonaut/railgun/blob/master/src/railgun/request.rs) but [defer deserializing into the handler themselves](https://github.com/aergonaut/railgun/blob/master/src/railgun/handlers/webhooks.rs#L12-L19) which seem (to me), like this goes again the Rocket way of doing things.

## General Comments

It was discussed on IRC, but it was late here is an excerpt of the conversation:

<details>
carreau

> Hi all, I do have a small question about data-guards in rocket (i'm relatively new to rust), It may be a question of vocabulary but I don't seem to be able to find an answer.  Is it possible to chain Data Guards ? More specifically I want to write a data-guard that check that hash(secret+data.body) == value-in-header but to do so need to consume Data. I can't recreate it (necessary things are private), and would like to not re-implement the all the existing From Data. Or maybe I am trying o do things the wrong way. Thanks.

Sergio

> What do you want to do with the data?
> Yes, you can chain guards. 

carreau

> Typically:
> #[post("/gh", data = "<payload>")]
> fn webhook_post(payload: SignedPayload<Json<Value>>) -> Whatever
> But I want Json<Value> to be variable

Sergio

> Yeah. 
> Hmm. Not sure if this can be done efficiently at the moment. 
> Assuming you can compute the hash in a streaming fashion, which should be the case, I'd implement a new data guard that wraps another data guard that somehow streams the data through the hash and into the other guard.
...
> This is interesting. I think the current API forces you to read the data into memory. 
> We should fix that. 
> 
So, this might not actually be possible. Even if you read everything into memory, you wouldn't be able to call the other FromData since the original Data is gone.

carreau 

> I guess a peek_all() that return the full buffer would be sufficient (inefficient for sure... but sufficient).

Sergio 

> We need some kind of way to provide a chain of readers to Data itself. 
> No, we won't add that.
> It makes DOS trivial. 
> Far too error prone.
> We need something like a .map method on Data that returns another Data but also makes mapping an error.
> Can you open an issue on GitHub with your usecase? I'm off to bed now but will think of a design that works for tomorrow.
> But also makes mapping fallible*

</details>

Apologies for any vocabulary that might be off I'm still relatively new to rust. Feel free to edit to make clearer.

Thanks.

**Comment by NilsIrl** [comment]
This would also allow to `Forward` even when data has been read. A use case for this is to have multiple struct-s for different JSON data.

**Comment by NilsIrl** [comment]
https://github.com/SergioBenitez/Rocket/blob/ca4d1572d408fd8dd13db103926ad96da878126d/core/lib/src/data/data.rs#L50-L53

How can all the data not be available for reading?

**Comment by jebrosen** [comment]
> How can all the data not be available for reading?

`Data` can only be read from once, since it is a live connection to the client. Allowing the data to be read twice requires some more work, such as one of these vague ideas:

* **duplicating** the data stream to a buffer in memory. This is generally not suitable for large requests. However, it is in many ways the most obvious solution and I think it's worth considering exposing something like `Data::from_bytes()` so that this can be implemented if desired.
* **forking** the data stream so that two consumers can read from it simultaneously. This sounds tricky to implement and to use properly.
* A **pass-through** mechanism, which is similar to forking the stream but with only one consumer actively controlling the read rate:

```rust
let mut count = 0;
let data = data.open().inspect(|bytes| {
    // This just counts the number of bytes received.
    // A more interesting implementation might hash them instead.
    count += bytes.len();
});
// OtherGuardType's FromData implementation will repeatedly `read` from the data as usual,
// and `inspect` will be called repeatedly throughout that process
let other_result = OtherGuardType::from_data(data)?;
```

**Comment by SergioBenitez** [comment]
We won't get this in for `0.5`. Pushing to `0.6`.

**Comment by KatsuoRyuu** [comment]
I would suggest Data implements a read that is going to read the stream into a Vec<u8>, if its bigger than eg 10MB offload the data to a temporary file, and replace the stream with a file stream.

We are currently very much need this ;)

**Comment by Stargateur** [comment]
> 
> 
> I would suggest Data implements a read that is going to read the stream into a Vec, if its bigger than eg 10MB offload the data to a temporary file, and replace the stream with a file stream.
> 
> We are currently very much need this ;)

do that for every implementation even if 99% of them don't need this ? why stop user side to implement this ? I fail to understand this issue.

> A use case for this is to have multiple struct-s for different JSON data.

That an anti pattern, one should deserialize into a struct that contain all you want to deserialize than you can split it as you like. I always fail to clearly see what is the purpose here.

**Comment by the10thWiz** [comment]
> > How can all the data not be available for reading?
> 
> `Data` can only be read from once, since it is a live connection to the client. Allowing the data to be read twice requires some more work, such as one of these vague ideas:
> 
> * **duplicating** the data stream to a buffer in memory. This is generally not suitable for large requests. However, it is in many ways the most obvious solution and I think it's worth considering exposing something like `Data::from_bytes()` so that this can be implemented if desired.
> * **forking** the data stream so that two consumers can read from it simultaneously. This sounds tricky to implement and to use properly.
> * A **pass-through** mechanism, which is similar to forking the stream but with only one consumer actively controlling the read rate:
> 
> ```rust
> let mut count = 0;
> let data = data.open().inspect(|bytes| {
>     // This just counts the number of bytes received.
>     // A more interesting implementation might hash them instead.
>     count += bytes.len();
> });
> // OtherGuardType's FromData implementation will repeatedly `read` from the data as usual,
> // and `inspect` will be called repeatedly throughout that process
> let other_result = OtherGuardType::from_data(data)?;
> ```

Duplicating the stream is obviously impractical, and forking the stream would require both to read at the same rate (or cause the same issues as duplicating the stream). Both suffer from performance and RAM usage issues for large requests.

However, I think the pass-though mechanism is much better. I do think that it should occur before the `open` call, since the idea is that the inspect has NO control over what data is read an when, they just get to inspect the bytes read. Other than that, there are a few potential issues I see. First, how many inspectors should be allowed? I would assume for performance reasons we would only want to allow one, otherwise we might need to allocate a Vector. What happens when a second inspect is added anyway? Well, we could allow one of them to inspect the stream (probably the first one), but I think we should at least try to provide reasonable error checking. Here, I think the best option would be to make the inspect function look like: `fn inspect(self, f: T) -> Result<(Data, T), _>`. In this case, it is assumed that the FromData implementation should fail if there is already another inspector.

The idea is that this is specifically only intended to support the use case of hashing or validating a signature, NOT supporting multiple types of data. If there are multiple possible forms of data, an enum (which has variants for each possible struct), is the best awnser.

Alternatively, we could support some type of hashing within Rocket, by providing the option to extract a hash/checksum of the data. I assume this would more or less just be a more limited version of the above proposal.

**Comment by SergioBenitez** [comment]
A draft of this functionality is now available in the `data-transformers` branch. In short, it introduces a new trait `Transform` and a type `TransformBuf` that allow you to do in-place transformations of streaming data:

```rust
/// ```text
/// [                    capacity                     ]
/// [       initialized        |     uninitialized    ]
/// [ +++ filled +++ | -------- unfilled              ]
///       ^------ cursor
/// ```
///
/// ```text
/// [ ++++*+++++++++++---------xxxxxxxxxxxxxxxxxxxxxxx]
/// ```
///
/// * `+`: filled (implies initialized)
/// * `*`: cursor position (implies filled)
/// * `-`: unfilled (implies initialized)
/// * `x`: uninitialized (implies unfilled)
pub struct TransformBuf<'a, 'b> {
    pub(crate) buf: &'a mut ReadBuf<'b>,
    pub(crate) cursor: usize,
}

pub trait Transform {
    fn poll_transform(
        self: Pin<&mut Self>,
        buf: &mut TransformBuf<'_, '_>,
    ) -> io::Result<()>;

    fn poll_finish(
        self: Pin<&mut Self>,
        cx: &mut Context<'_>,
        buf: &mut TransformBuf<'_, '_>,
    ) -> Poll<io::Result<()>> {
        let (_, _) = (cx, buf);
        Poll::Ready(Ok(()))
    }
}
```

Convenience methods allow you to make use of this functionality for common cases easily:

```rust
data.chain_inspect(|bytes| println!("INIT: ({}) {bytes:X?}", bytes.len()))
    .chain_hash_transform(DefaultHasher::new())
    .chain_inspect(|bytes| println!("HASH: ({}) {bytes:X?}", bytes.len()));
```

When `{"foo": "bar"}` is sent as data, the logs yield:

```rust
INIT: (14) [7B, 22, 66, 6F, 6F, 22, 3A, 20, 22, 62, 61, 72, 22, 7D]
HASH: (8) [A5, DA, E5, DB, E6, 2D, 41, B7]
```

This demonstrates that the data stream is modified in-place.

Any commentary and/or feedback is appreciated.

**Comment by martynp** [comment]
I have had a play and can modify data with something along the lines of:

```rust
pub struct HMACHash {
    sha256_hasher: Sha256,
    buffer: Option<Vec<u8>>,
    output: Option<std::io::Cursor<Vec<u8>>>,
}

impl HMACHash {
    pub fn new() -> Self {
        Self {
            sha256_hasher: Sha256::new(),
            buffer: Some(Vec::new()),
            output: None,
        }
    }
}

use rocket::tokio::io::AsyncRead;
use std::convert::TryInto;

impl rocket::data::Transform for HMACHash {
    fn poll_transform(
        mut self: std::pin::Pin<&mut Self>,
        buf: &mut rocket::data::TransformBuf<'_, '_>,
    ) -> std::io::Result<()> {
        self.buffer.as_mut().unwrap().extend_from_slice(buf.fresh());
        buf.spoil();
        Ok(())
    }

    fn poll_finish(
        mut self: Pin<&mut Self>,
        cx: &mut std::task::Context<'_>,
        buf: &mut rocket::data::TransformBuf<'_, '_>,
    ) -> std::task::Poll<std::io::Result<()>> {
        if self.output.is_none() {
            let hash = self.sha256_hasher.clone().finalize().to_vec();
            let hash: [u8; 32] = hash.try_into().unwrap();
            let digest = general_purpose::STANDARD.encode(&hash);
            self.buffer.as_mut().unwrap().extend_from_slice(&digest.as_bytes());

            self.output = Some(std::io::Cursor::new(self.buffer.take().unwrap()));
        }

        let cursor = self.output.as_mut().unwrap();
        Pin::new(cursor).poll_read(cx, buf)
    }
}
```

I could then process the output to remove and process the result as part of a HMAC regime. It is improved, but does seem a bit inelegant.

Is there a way to allow the data transform to access the owning Request object?

**Comment by martynp** [comment]
> Is there a way to allow the data transform to access the owning Request object?

After a lot of digging, I am thinking this functionality might actually be impractical with the way the data and handlers are separated using the above aproach?

Or at the very least, it will be adding some overhead per-request which is excessive...

**Comment by SergioBenitez** [comment]
> I have had a play and can modify data with something along the lines of:
> 
> 
> 
> ```rust
> 
> pub struct HMACHash {
> 
>     sha256_hasher: Sha256,
> 
>     buffer: Option<Vec<u8>>,
> 
>     output: Option<std::io::Cursor<Vec<u8>>>,
> 
> }
> 
> 
> 
> impl HMACHash {
> 
>     pub fn new() -> Self {
> 
>         Self {
> 
>             sha256_hasher: Sha256::new(),
> 
>             buffer: Some(Vec::new()),
> 
>             output: None,
> 
>         }
> 
>     }
> 
> }
> 
> 
> 
> use rocket::tokio::io::AsyncRead;
> 
> use std::convert::TryInto;
> 
> 
> 
> impl rocket::data::Transform for HMACHash {
> 
>     fn poll_transform(
> 
>         mut self: std::pin::Pin<&mut Self>,
> 
>         buf: &mut rocket::data::TransformBuf<'_, '_>,
> 
>     ) -> std::io::Result<()> {
> 
>         self.buffer.as_mut().unwrap().extend_from_slice(buf.fresh());
> 
>         buf.spoil();
> 
>         Ok(())
> 
>     }
> 
> 
> 
>     fn poll_finish(
> 
>         mut self: Pin<&mut Self>,
> 
>         cx: &mut std::task::Context<'_>,
> 
>         buf: &mut rocket::data::TransformBuf<'_, '_>,
> 
>     ) -> std::task::Poll<std::io::Result<()>> {
> 
>         if self.output.is_none() {
> 
>             let hash = self.sha256_hasher.clone().finalize().to_vec();
> 
>             let hash: [u8; 32] = hash.try_into().unwrap();
> 
>             let digest = general_purpose::STANDARD.encode(&hash);
> 
>             self.buffer.as_mut().unwrap().extend_from_slice(&digest.as_bytes());
> 
> 
> 
>             self.output = Some(std::io::Cursor::new(self.buffer.take().unwrap()));
> 
>         }
> 
> 
> 
>         let cursor = self.output.as_mut().unwrap();
> 
>         Pin::new(cursor).poll_read(cx, buf)
> 
>     }
> 
> }
> 
> ```
> 
> 
> 
> I could then process the output to remove and process the result as part of a HMAC regime. It is improved, but does seem a bit inelegant.
> 
> 
> 
> Is there a way to allow the data transform to access the owning Request object?

Your reimplementation is inefficient. There's no reason to store the entire data buffer. Implementations like this should be strictly avoided:

```rust
self.buffer.as_mut().unwrap().extend_from_slice(buf.fresh());
```

The primary purpose of this API is to allow you to stream data and modify it in place. Buffering the data defeats that intent. I understand that there aren't any docs as of yet, but please see the hasher example in the commit (`HashTransform`). In fact, I'll copy it here:

```rust
mod hash_transform {
    use std::io::Cursor;
    use std::hash::Hasher;

    use tokio::io::AsyncRead;

    use super::*;

    pub struct HashTransform<H: Hasher> {
        pub(crate) hasher: H,
        pub(crate) hash: Option<Cursor<[u8; 8]>>
    }

    impl<H: Hasher + Unpin> Transform for HashTransform<H> {
        fn poll_transform(
            mut self: Pin<&mut Self>,
            // cx: &mut Context<'_>,
            buf: &mut TransformBuf<'_, '_>,
        ) -> io::Result<()> {
            self.hasher.write(buf.fresh());
            buf.spoil();
            Ok(())
        }

        fn poll_finish(
            mut self: Pin<&mut Self>,
            cx: &mut Context<'_>,
            buf: &mut TransformBuf<'_, '_>,
        ) -> Poll<io::Result<()>> {
            if self.hash.is_none() {
                let hash = self.hasher.finish();
                self.hash = Some(Cursor::new(hash.to_be_bytes()));
            }

            let cursor = self.hash.as_mut().unwrap();
            Pin::new(cursor).poll_read(cx, buf)
        }
    }
}
```

It implements the behavior you're looking for. The only necessary change would be to remove the call to spoil() in the transform method implementation of that example. That allows the original data to be passed through without modification.

**Comment by SergioBenitez** [comment]
> > Is there a way to allow the data transform to access the owning Request object?
> 
> 
> 
> After a lot of digging, I am thinking this functionality might actually be impractical with the way the data and handlers are separated using the above aproach?
> 
> 
> 
> Or at the very least, it will be adding some overhead per-request which is excessive...

I'm not sure what you mean by "owning" request object. It would be possible to pass the request object to the finish method, but I'm not sure it's necessary. There are two things you can do without direct access to the request method in the transformer. The first is to share state between the transformer and request local  state. That is, store an Arc in the request local cache and pass it to the transformer when it's created. Then you can modify it as you wish in the finish method and retrieve the state again from the request whenever you'd like. The second second is to inject data into the stream and have a data guard that can interpret it. Both of these are viable solutions to almost any use case I can consider without being work-arounds. However should there be an important use case that requires access to the request, I'd be all ears.

**Comment by martynp** [comment]
> > > Is there a way to allow the data transform to access the owning Request object?
> > 
> > 
> > After a lot of digging, I am thinking this functionality might actually be impractical with the way the data and handlers are separated using the above aproach?
> > Or at the very least, it will be adding some overhead per-request which is excessive...
> 
> I'm not sure what you mean by "owning" request object. It would be possible to pass the request object to the finish method, but I'm not sure it's necessary. There are two things you can do without direct access to the request method in the transformer. The first is to share state between the transformer and request local state. That is, store an Arc in the request local cache and pass it to the transformer when it's created. Then you can modify it as you wish in the finish method and retrieve the state again from the request whenever you'd like. The second second is to inject data into the stream and have a data guard that can interpret it. Both of these are viable solutions to almost any use case I can consider without being work-arounds. However should there be an important use case that requires access to the request, I'd be all ears.

I hadn't considered putting an Arc in the local store, should work nicely. I will have another look tomorrow and post back results.

**Comment by martynp** [comment]
Had a bit more of a play, looks to be working well:

https://gist.github.com/martynp/a9e48d33562130ddd65d86df1183f6c1

The reason I was looking at buffering the complete buffer was to implement request compression processing:

```rust

...
        let encoding = req.headers().get_one("Content-Encoding");
        if encoding.is_some() && encoding.unwrap() == "deflate" {
            data.chain_transform(ZlibCompression::new())
        }
...

use flate2::read::ZlibDecoder;
use rocket::tokio::io::AsyncRead;

pub struct ZlibCompression {
    buffer: Vec<u8>,
    output: Option<std::io::Cursor<Vec<u8>>>,
}

impl ZlibCompression {
    pub fn new() -> Self {
        Self {
            buffer: Vec::new(),
            output: None,
        }
    }
}

impl rocket::data::Transform for ZlibCompression {
    fn poll_transform(
        mut self: std::pin::Pin<&mut Self>,
        buf: &mut rocket::data::TransformBuf<'_, '_>,
    ) -> std::io::Result<()> {
        self.buffer.extend_from_slice(buf.fresh());
        buf.spoil();
        Ok(())
    }

    fn poll_finish(
        mut self: Pin<&mut Self>,
        cx: &mut std::task::Context<'_>,
        buf: &mut rocket::data::TransformBuf<'_, '_>,
    ) -> std::task::Poll<std::io::Result<()>> {
        if self.output.is_none() {
            let mut decoder = ZlibDecoder::new(&self.buffer[..]);
            let mut buffer = Vec::new();
            decoder.read_to_end(&mut buffer).unwrap();
            self.output = Some(std::io::Cursor::new(buffer));
        }

        let cursor = self.output.as_mut().unwrap();
        Pin::new(cursor).poll_read(cx, buf)
    }
}
```

I am sure there is a better way to get it to work, but I don't believe there is an easy way to push arbitrary blocks of data to the decompression crate. And in any case I believe it would probably end up buffering the (larger) output in any case.

**Comment by charlesportwoodii** [comment]
Hi there - `data.chain_inspect` seems to work well enough inside of data guards for any stream modifications that need to be done, but falls short if the request body is necessary for any authentication calculation (as an example, AWS Signature Version 4 **with payload signing**), if I'm implementation authentication as a forwarding guard check

The payload signature is the significant element here, as verifying the request requires reading the request body to validate that the signature matches the body, which then determines whether authentication succeeds or not.

For example, if I'm looking to implement authentication as a forwarding guard I'd expect the following - the problem being that the forwarding guard can't access the data to perform the check.
```rust
#[get("/admin", data = "<data>")]
fn admin_panel_user(
    data: rocket::Json<MyStruct>,
    user: User //// <------ Forwarding guards don't have access to request body to perform payload signing checks
) -> &'static str {
    "User is authenticated"
}
```

`from_data` in the data guard executes after `from_request` in the forwarding guard, which with this implementation I still don't think provides a workaround for implementing AWS Signature Auth with payload signing, or similar auth schemes. The data just isn't accessible at the point in time it's needed.

Is there a way to  have the data available either in a fairing, or a forwarding guard? I understand that I can Arc the data out of `chain_inspect`, but that doesn't get around the data not being available in a forwarding guard or a fairing for authentication if I'm looking to implement AWS Signature Version 4 auth with payload signing on the server.

If I'm missing something obvious please let me know. I appreciate your help.

**Comment by SergioBenitez** [comment]
@charlesportwoodii Implement the check in the data guard, not the request guard. This is checking the data, after all. Something like this:

```rust
struct Authenticated<R, D> {
    role: R,
    data: D,
}

#[rocket::async_trait]
impl<'r, R: Role, D: FromData<'r>> FromData<'r> for Authenticated<R, D> {
    type Error = D::Error;

    async fn from_data(req: &'r Request<'_>, data: Data<'r>) -> data::Outcome<'r, Self> {
        let sig = Signature::new();
        let chained = data.chain_inspect(|bytes| sig.update(bytes));
        let data = try_outcome!(F::from_data(req, data).await);
        if !sig.matches(req.headers().get("X-Signature") {
            return Outcome::Forward(..);
        }

        Outcome::Success(Authenticated(R::from(req), data))
    }
}
```

> Is there a way to have the data available either in a fairing, or a forwarding guard?

No. That would either imply copying the data, which Rocket completely avoids and makes it very hard for your application to do, or making the data readable from multiple places at once, which opens up your application to logic bugs as this would be implicitly shared, mutable state. Rocket is unlikely to ever allow either.

The idea behind chainable transforms is to enable the kind of functionality other frameworks succumb to copying data for without doing so. I think my proposal and implementation accomplishes this elegantly. If for whatever reason the above pseudocode is not sufficient, please let me know.
